development:
  adapter: postgresql
  database: considerit_dev
  username: root
  password: root
  host: localhost

test:
  adapter: postgresql
  database: considerit_test
  password: root
  host: localhost

production:
  adapter: postgresql
  database: considerit_production
  username: root
  password: root
  host: localhost


