development:
  adapter: postgresql
  database: lvg2_dev
  username: root
  password: root
  host: localhost

test:
  adapter: postgresql
  database: dub_test
  password: root
  host: localhost

production:
  adapter: postgresql
  database: dub_production
  username: root
  password: root
  host: localhost


