development:
  adapter: postgresql
  database: considerit_dev
  username: root
  password: 
  host: localhost
  port: 5432

test:
  adapter: postgresql
  database: considerit_test
  username: root
  password: 
  host: localhost
  port: 5432

production:
  adapter: postgresql
  database: considerit_production
  username: root
  password: 
  host: localhost


