development: 
  app_name: 
    short: HPEP
    long: Health E Public
  
  theme: lvg
  
  meta:
    title: Health E Public
    subtitle: Increase awareness of the role of socio-economic status in public health
    
  perform_authentication: true
  send_email: false
  
  default_from_email: ghconsiderit@gmail.com
  email_head: Health E Public
    
  home:
    call: A discussion on public health
    subcall: powered by everyone
    values:
      - lead: Organize your thoughts...
        follow: Write a pro/con list for each idea.
      - lead: Cut through the preconceptions...
        follow: Hear what other people think. 
      - lead: Take the initiative...
        follow: Add your own voice to the discussion.
  
  socmedia:
    facebook:
      include_follow: false
      facebook_page: "http://www.facebook.com/pages/Living-Voters-Guide/157151824312366"
    twitter:
      include_follow: false
      twitter_page: "http://www.twitter.com/LVGuide"
  
  decisions:
    name: 
      short: option
      full: Option
  
  footer:
    has_custom_resources: true
    resources:
      - title: Health E Public
        items:
          - anchor: Population Health Forum by UW
            link: http://depts.washington.edu/eqhlth/
            title: Population Health Forum by UW
      
         
  
test: 
  default_to: development


production:
  default_to: development

